# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Camera3DDepth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Camera3DDepth
  pod 'PeerTalk'

  target 'Camera3DDepthTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Camera3DDepthUITests' do
    # Pods for testing
  end

end
